export const GET_PROJECTS_PENDING = 'PROJECTS/GET_PROJECTS_PENDING';
export const GET_PROJECTS_SUCCESS = 'PROJECTS/GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_FAIL = 'PROJECTS/GET_PROJECTS_FAIL';
