export const ADD_TASK = 'TODO/ADD_TASK';
export const ADD_SUB_TASK = 'TODO/ADD_SUB_TASK';
export const CHANGE_TASK_TITLE = 'TODO/CHANGE_TASK_TITLE';
export const CHANGE_IS_EXPENDED = 'TODO/CHANGE_IS_EXPENDED';
