export const ADD_TASK = 'TODO/ADD_TASK';
export const ADD_SUB_TASK = 'TODO/ADD_SUB_TASK';
export const DELETE_TASK = 'TODO/DELETE_TASK';
export const CHANGE_TASK_TITLE = 'TODO/CHANGE_TASK_TITLE';
export const CHANGE_IS_EXPENDED = 'TODO/CHANGE_IS_EXPENDED';
export const ITEM_ID_TO_MOVE = 'TODO/ITEM_ID_TO_MOVE';
export const CONFIRM_CHANGE_POS = 'TODO/CONFIRM_CHANGE_POS';
export const CHANGE_IS_CHECKED = 'TODO/CHANGE_IS_CHECKED';
